name = input('Enter your name ')
last_name = input('Enter your last name ')
phone = input('Enter your phone number ')
street = input('Enter the street where you live ')
house = input('Enter your house number ')
apartment = input('Enter your apartment number ')
city = input('Enter the city where you live ')
zip_code = input('Enter your zip code ')
country = input('Enter the country in which you live ')
print(name, last_name)
print(phone)
print('Str.', street, house,', ap.', apartment,',', city)
print(zip_code)
print(country)